# Generated by Django 5.2.13 on 2026-05-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="barbeiro",
            name="percentual_comissao",
            field=models.DecimalField(
                decimal_places=2,
                default=40,
                max_digits=5,
                verbose_name="Percentual de Comissão",
            ),
        ),
    ]
