# Generated by Django 5.2.13 on 2026-05-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0002_barbeiro_percentual_comissao"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("confirmado", "Confirmado"),
                    ("cancelado", "Cancelado"),
                    ("concluido", "Concluído"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
