# Generated by Django 5.2.13 on 2026-06-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0003_agendamento_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
